### ISSUE TITLE
Installed rcon plugin. Got Error message when using rcon command.

### ISSUE THREAD

**Issue by marcoroegner** [ich777/unraid-rcon#1]
### Install Output
plugin: installing: rcon.plg
Executing hook script: pre_plugin_checks
plugin: downloading: rcon.plg ... done

plugin: downloading: rcon-2022.02.17.txz ... done

+==============================================================================
| Installing new package /boot/config/plugins/rcon/rcon-2022.02.17.txz
+==============================================================================

Verifying package rcon-2022.02.17.txz.
Installing package rcon-2022.02.17.txz:
PACKAGE DESCRIPTION:
plugin: downloading: libbsd-0.10.0-x86_64-2_slonly.txz ... done

+==============================================================================
| Skipping package libbsd-0.10.0-x86_64-2_slonly (newer vesion already installed)
+==============================================================================

plugin: rcon.plg installed
Executing hook script: post_plugin_checks

### Error Message
rcon -h
rcon: error while loading shared libraries: libmd.so.0: cannot open shared object file: No such file or directory

**Comment by ich777** [comment]
Thank you for the report, can you please share your Diagnostics?

**Comment by ich777** [comment]
Please update the plugin to version 2023.04.23 and the issue should be fixed.

**Comment by marcoroegner** [comment]
Thank you.
